// Catppuccin Mocha palette
export const palette = {
  rosewater: '#f5e0dc',
  flamingo:  '#f2cdcd',
  pink:      '#f5c2e7',
  mauve:     '#cba6f7',
  red:       '#f38ba8',
  maroon:    '#eba0ac',
  peach:     '#fab387',
  yellow:    '#f9e2af',
  green:     '#a6e3a1',
  teal:      '#94e2d5',
  sky:       '#89dceb',
  sapphire:  '#74c7ec',
  blue:      '#89b4fa',
  lavender:  '#b4befe',
  text:      '#cdd6f4',
  subtext1:  '#bac2de',
  subtext0:  '#a6adc8',
  overlay2:  '#9399b2',
  overlay1:  '#7f849c',
  overlay0:  '#6c7086',
  surface2:  '#585b70',
  surface1:  '#45475a',
  surface0:  '#313244',
  base:      '#1e1e2e',
  mantle:    '#181825',
  crust:     '#11111b',
};

export const xtermTheme = {
  foreground:      palette.text,
  background:      palette.base,
  cursor:          palette.rosewater,
  cursorAccent:    palette.base,
  selectionBackground: palette.surface2 + '80',
  selectionForeground: palette.text,
  black:           palette.surface1,
  red:             palette.red,
  green:           palette.green,
  yellow:          palette.yellow,
  blue:            palette.blue,
  magenta:         palette.pink,
  cyan:            palette.teal,
  white:           palette.subtext1,
  brightBlack:     palette.overlay0,
  brightRed:       palette.red,
  brightGreen:     palette.green,
  brightYellow:    palette.yellow,
  brightBlue:      palette.blue,
  brightMagenta:   palette.pink,
  brightCyan:      palette.teal,
  brightWhite:     palette.text,
};
